name: atlantis-terraform-awx

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: evit15/atlantis-terraform-awx:latest
